#server:
#  servlet:
#    session:
#      cookie:
#        max-age: 172800

spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    password:
    url: jdbc:h2:mem:test
  jpa:
    show-sql: true
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
  data:
    web:
      pageable:
        # 이거 적용 될려면 web 으로부터 요청이 왔을 때 의미 있다.
        # 내부에 직접 PageRequest 를 만들었을 경우 의미 없음
        one-indexed-parameters: true
        default-page-size: 5
  session:
    timeout: 86400  # 하루
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id:  # {client-id}
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            scope:
              - profile_nickname
              - profile_image
              - account_email
              - gender
              - birthday
            client_name: kakao
          google:
            client-id: client-id # {client-id}
            client-secret: secret # {secret}
            client-name: google
          naver:
            client-id: client-id # {client-id}
            client-secret: secret # {secret}
            client-name: naver
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            scope:
              - name
              - email
#              - 원하는 것들 추가
            authorization-grant-type: authorization_code
            client-authentication-method: POST
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          naver:
            authorization_uri: https://nid.naver.com/oauth2.0/authorize
            token_uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user_name_attribute: response

